# Generated by Django 5.2 on 2025-05-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0002_chat_lastmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profilepicture",
            field=models.ImageField(default="", upload_to="profilepictures"),
        ),
    ]
